### PR TITLE
Added Dark Mode

### PR DESCRIPTION
**Pull request by afallon02**
This pull request will add a dark mode to this project

### CODE REVIEW

**Comment by oNaiPs** [comment]
@afallon02 sorry for the delay answering you. Looking good!
Left a few comments

**Comment by afallon02** [comment]
hey @oNaiPs Am I being stupid or did you comments not post? I can't see anything

**Comment by oNaiPs** [comment]
> hey @oNaiPs Am I being stupid or did you comments not post? I can't see anything

Sorry @afallon02 I forgot to post the comments :| You should be able to see them now

**Comment by oNaiPs** [comment]
@afallon02 any news on this PR?

**Comment by oNaiPs** [comment]
Closing this as it seems that dark mode is automatically supported by the app.

**Pull request closed without merging**
