### PR TITLE
feat: add tabbing support

### PR DESCRIPTION
**Pull request by antoniocapelo**
### What

Added Tab / Shift-Tab support for quickly browsing through result list

### How

Removed previous tab behaviour (which was clearing the list on unexpected occasions) and added support for tab / shift-tab selectors.

### Note

I'm not proficient in mac os app development, I mostly work on web development, so if I'm committing anything I shouldn't, please say so :-) 

Also, thanks for doing this *d-menu* port, it's good to have a quick and simple alternative to Spotlight!

### CODE REVIEW

**Comment by antoniocapelo** [comment]
@oNaiPs friendly ping :-)

**Comment by antoniocapelo** [comment]
👋

**Comment by vladdoster** [comment]
@oNaiPs Could this get merged or get feedback on changes that would allow this to be merged?

**Review by oNaiPs — CHANGES_REQUESTED** [review]
Apologies for the delay - I just realized that I started the review but never hit "Request changes" :(
Will try to expedite the review. Thanks!

**Comment by oNaiPs** [comment]
@antoniocapelo pushed a version of this to `master`. Look out for the next release.. many thanks!

**Pull request closed without merging**
